# Generated by Django 6.0.2 on 2026-03-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_combo_comboitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='icon',
            field=models.CharField(blank=True, default='🎁', help_text='Emoji icon e.g. 🎁', max_length=50),
        ),
    ]
